### ISSUE TITLE
separate want to play+own from wishlist+for trade

### ISSUE THREAD

**Issue by mszczerbak** [mszczerbak/bgg-gaming-group-tools#9]
the two are not the same, as the first is just for playing the game together, the second for trading one

**Comment by mszczerbak** [comment]
and separate from "people want but no-one has" -> action of crowd-testing ;)

the three can be on the same page but there should be a switch to change the context

**Comment by teriblus** [comment]
I don't use the "fortrade" as an equivalent to "want to play"

I mixed "wishlist", "want", "want to play", "want to buy" together though, because I concidered that when you want to buy a game, you also want to play it !

I kept "people want but no-one has" because I thought it would be a good feature to determine games that should be purchased by one of the people who want the game or by parties civiles.

**Comment by mszczerbak** [comment]
https://github.com/mszczerbak/bgg-gaming-group-tools/pull/11
